version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: "postgres-container"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - my-pg-data:/var/lib/postgresql/data
    networks:
      - two-tier
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  node-backend:
    build:
      context: .
    container_name: "node-backend-container"
    environment:
      PG_USER: "postgres"
      PG_DB: "postgres"
      PG_PASSWORD: "password"
      PG_HOST: "postgres"
    ports:
      - "3000:3000"
    networks:
      - two-tier
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  my-pg-data:

networks:
  two-tier:
